/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/page.test`; params?: Router.UnknownInputParams; } | { pathname: `/page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/page`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard/page`; params?: Router.UnknownInputParams; } | { pathname: `/admin/login/page`; params?: Router.UnknownInputParams; } | { pathname: `/api/add-bleed/route`; params?: Router.UnknownInputParams; } | { pathname: `/api/change-colors/route`; params?: Router.UnknownInputParams; } | { pathname: `/api/convert-outlines/route`; params?: Router.UnknownInputParams; } | { pathname: `/api/remove-bleed/route`; params?: Router.UnknownInputParams; } | { pathname: `/api/upload/route.test`; params?: Router.UnknownInputParams; } | { pathname: `/api/upload/route`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/page.test`; params?: Router.UnknownOutputParams; } | { pathname: `/page`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/page`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/dashboard/page`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/login/page`; params?: Router.UnknownOutputParams; } | { pathname: `/api/add-bleed/route`; params?: Router.UnknownOutputParams; } | { pathname: `/api/change-colors/route`; params?: Router.UnknownOutputParams; } | { pathname: `/api/convert-outlines/route`; params?: Router.UnknownOutputParams; } | { pathname: `/api/remove-bleed/route`; params?: Router.UnknownOutputParams; } | { pathname: `/api/upload/route.test`; params?: Router.UnknownOutputParams; } | { pathname: `/api/upload/route`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/layout${`?${string}` | `#${string}` | ''}` | `/page.test${`?${string}` | `#${string}` | ''}` | `/page${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/page${`?${string}` | `#${string}` | ''}` | `/admin/dashboard/page${`?${string}` | `#${string}` | ''}` | `/admin/login/page${`?${string}` | `#${string}` | ''}` | `/api/add-bleed/route${`?${string}` | `#${string}` | ''}` | `/api/change-colors/route${`?${string}` | `#${string}` | ''}` | `/api/convert-outlines/route${`?${string}` | `#${string}` | ''}` | `/api/remove-bleed/route${`?${string}` | `#${string}` | ''}` | `/api/upload/route.test${`?${string}` | `#${string}` | ''}` | `/api/upload/route${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/page.test`; params?: Router.UnknownInputParams; } | { pathname: `/page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/page`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard/page`; params?: Router.UnknownInputParams; } | { pathname: `/admin/login/page`; params?: Router.UnknownInputParams; } | { pathname: `/api/add-bleed/route`; params?: Router.UnknownInputParams; } | { pathname: `/api/change-colors/route`; params?: Router.UnknownInputParams; } | { pathname: `/api/convert-outlines/route`; params?: Router.UnknownInputParams; } | { pathname: `/api/remove-bleed/route`; params?: Router.UnknownInputParams; } | { pathname: `/api/upload/route.test`; params?: Router.UnknownInputParams; } | { pathname: `/api/upload/route`; params?: Router.UnknownInputParams; };
    }
  }
}
